"""Add time_limit to competition_quizzes

Revision ID: 32d09d7ef2a3
Revises: 5f091fb12172
Create Date: 2025-02-03 10:19:43.190110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d09d7ef2a3'
down_revision = '5f091fb12172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True, comment='Duración máxima en segundos para completar el cuestionario'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
