"""Add processed to competition_quizzes

Revision ID: 40c36011e5fd
Revises: ee1f4012732d
Create Date: 2025-02-04 10:26:34.710687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c36011e5fd'
down_revision = 'ee1f4012732d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=True, comment='Indica si ya se procesaron los resultados'))
        batch_op.create_index(batch_op.f('ix_competition_quizzes_processed'), ['processed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_quizzes_processed'))
        batch_op.drop_column('processed')

    # ### end Alembic commands ###
