"""answers

Revision ID: 5e87b98eb93b
Revises: 861516303c83
Create Date: 2025-01-30 08:50:20.856947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e87b98eb93b'
down_revision = '861516303c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_quiz_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_quiz_id'], ['competition_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_quiz_id', 'participant_id', 'answer_id', name='uq_quiz_participant_answer')
    )
    with op.batch_alter_table('competition_quiz_answers', schema=None) as batch_op:
        batch_op.create_index('idx_quiz_participant', ['competition_quiz_id', 'participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quiz_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_quiz_participant')

    op.drop_table('competition_quiz_answers')
    # ### end Alembic commands ###
