"""add competition quiz participant

Revision ID: 861516303c83
Revises: ee4e43bef5a0
Create Date: 2025-01-29 12:28:39.123848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861516303c83'
down_revision = 'ee4e43bef5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_quizzes_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_quiz_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competition_quiz_id'], ['competition_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_quiz_id', 'participant_id', name='uq_competition_quiz_participant')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competition_quizzes_participants')
    # ### end Alembic commands ###
