"""Edit status string in competition_quiz

Revision ID: d5cf92168c01
Revises: 7c23977f9265
Create Date: 2025-02-05 09:44:19.412121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5cf92168c01'
down_revision = '7c23977f9265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVO', 'COMPUTABLE', 'NO_COMPUTABLE', name='competitionquizstatus'),
               type_=sa.String(length=50),
               existing_comment='Estado del cuestionario dentro de la competencia',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quizzes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVO', 'COMPUTABLE', 'NO_COMPUTABLE', name='competitionquizstatus'),
               existing_comment='Estado del cuestionario dentro de la competencia',
               existing_nullable=False)

    # ### end Alembic commands ###
