"""Add score to competition_participant

Revision ID: ee1f4012732d
Revises: 32d09d7ef2a3
Create Date: 2025-02-03 21:32:36.854793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1f4012732d'
down_revision = '32d09d7ef2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True, comment='Puntaje acumulado del participante en la competencia.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_participants', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
