"""Fix unique constraint: use question_id instead of answer_id

Revision ID: fc4f9ff3c2a7
Revises: 1183cb7e4765
Create Date: 2025-04-08 09:57:03.436979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4f9ff3c2a7'
down_revision = '1183cb7e4765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quiz_participant_answer', type_='unique')
        batch_op.create_unique_constraint('uq_quiz_participant_answer', ['competition_quiz_id', 'participant_id', 'question_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_quiz_participant_answer', type_='unique')
        batch_op.create_unique_constraint('uq_quiz_participant_answer', ['competition_quiz_id', 'participant_id', 'answer_id'])

    # ### end Alembic commands ###
